# Generated by Django 3.2.9 on 2023-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211120_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.Category'),
        ),
    ]
