# Generated by Django 3.2.9 on 2023-02-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230205_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_home',
        ),
    ]
